### ISSUE TITLE
heapqueue scanning -- prioritize near cells

### ISSUE THREAD

**Issue by bukzor** [asottile/PokemonGo-Map#10]
Instead of mindlessly tracing a static pattern repeatedly, it would be preferable if the scanner actually understood the staleness of its cells and refreshed them appropriately.

I'd like to put a bell-curve distribution on the staleness tolerance of the cells; the center cell should be always completely up-to-date, but the cells on the fringe can be a bit more stale.

**Comment by asottile** [comment]
I'm abandoning my efforts in this project
