### ISSUE TITLE
Remove retrying_get_profile?

### ISSUE THREAD

**Issue by asottile** [asottile/PokemonGo-Map#15]
It seems to sometimes get in a state where it "received no-len payload" and will never recover from that.  Better to let it die and have pgctl restart it probably?

@bukzor thoughts?

**Comment by bukzor** [comment]
When I saw that issue, restarting gave the same result.

Currently I can only scrape a 7km area bc that seems to be how long the
login season lasts. I'd like to be able to scan large areas.

**Comment by asottile** [comment]
I'm using this patch btw with reasonable success:

``` diff
diff --git a/scrape.py b/scrape.py
index 73e2589..5fcba36 100644
--- a/scrape.py
+++ b/scrape.py
@@ -134,7 +134,7 @@ def retrying_get_profile(access_token, api, useauth, lat_i, lng_i):
             profile_response = None
             continue
         if not profile_response.payload:
-            print('retrying_get_profile: get_profile returned no-len payload, retrying')
+            raise AssertionError('retrying_get_profile: get_profile returned no-len payload, retrying')
             profile_response = None

     return profile_response
```

**Comment by asottile** [comment]
Via #32
